### Tous les collègues
GET https://app-6f6e9c23-7f63-4d86-975b-a0b1a1440f94.cleverapps.io/api/v2/colleagues

### Le détail d'un collègue
GET https://app-6f6e9c23-7f63-4d86-975b-a0b1a1440f94.cleverapps.io/api/v2/colleagues/gio01

### Créer un collègue
POST https://app-6f6e9c23-7f63-4d86-975b-a0b1a1440f94.cleverapps.io/api/v2/colleagues
Content-type: application/json

{
    "pseudo": "ross44",
    "last": "Oddet",
    "first": "Rossi",
    "photo": "https://randomuser.me/api/portraits/men/9.jpg"
}

### Les votes
GET https://app-6f6e9c23-7f63-4d86-975b-a0b1a1440f94.cleverapps.io/api/v2/votes
